[package]
name = "tzolkin"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
tauri = { version = "2.12.1", features = [] }
tauri-plugin-dialog = "2.8.1"
tauri-plugin-fs = "2.6.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
