pub(crate) const FIRST_FOOD_DAY: u32 = 8;
pub(crate) const SECOND_FOOD_DAY: u32 = 14;
pub(crate) const THIRD_FOOD_DAY: u32 = 21;
pub(crate) const FOURTH_FOOD_DAY: u32 = 27;
pub(crate) const CORN_PER_WORKER: u32 = 2; // food_dayでworker1人につき必要なコーン数
pub(crate) const TOP_BONUS_SECOND_FOOD_DAY_CHAAC: u32 = 6;
pub(crate) const TOP_BONUS_SECOND_FOOD_DAY_QUETZALCOATL: u32 = 2;
pub(crate) const TOP_BONUS_SECOND_FOOD_DAY_KUKULKAN: u32 = 4;
pub(crate) const TOP_BONUS_FOURTH_FOOD_DAY_CHAAC: u32 = 2;
pub(crate) const TOP_BONUS_FOURTH_FOOD_DAY_QUETZALCOATL: u32 = 6;
pub(crate) const TOP_BONUS_FOURTH_FOOD_DAY_KUKULKAN: u32 = 4;
