[package]
name = "tzolkin-ai"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
autotests = false

[dependencies]
tzolkin-core = { path = "../tzolkin-core" }
tzolkin-bot = { path = "../tzolkin-bot" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
sha2 = "0.10"

[[test]]
name = "all"
path = "tests/all.rs"
